baseURL = "https://blog.zhouhaibing.com/"
languageCode = "en-us"
title = "Hi-Been Space"
theme = "paper"
disqusShortname = "zhouhaibing089"

[params]
  color = 'gray'
  avatar = 'zhouhaibing089@gmail.com'
  name = 'Haibing Zhou'
  bio = "Obstacle is the way; Ego is the enemy."
  github = 'zhouhaibing089'
  linkedin = 'haibzhou'
