baseURL = "https://blog.zhouhaibing.com/"
languageCode = "en-us"
title = "Blog"
theme = "ananke"
pygmentsUseClasses = true
disqusShortname = "zhouhaibing089"

[params]
  custom_css = ["css/custom.css", "css/syntax.css"]
